backend/network4like/core/urls.py
from django.conf.urls import url, include

from core import views

app_name = 'core'
urlpatterns = [
	url(r'^$', views.home, name='index'),
	url(r'^(?P<pk>[0-9]+)/', views.exibir, name='exibir'),
]

backend/network4like/network4like/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'', include("core.urls", namespace="core")),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/network4like/core/models.py
from django.db import models

# Create your models here.
class Imagem(models.Model):
	file = models.ImageField("Arquivo", default="")
	qtd_likes = models.PositiveIntegerField('Quantidade de Likes', null=True, blank=True)
	qtd_followers = models.PositiveIntegerField('Quantidade de Followers')

backend/network4like/core/forms.py
from django import forms
from core.models import Imagem

class ImagemForm(forms.ModelForm):

	class Meta:
		model = Imagem
		fields=['file']

backend/network4like/core/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, reverse
from django.core.urlresolvers import reverse_lazy

from core.forms import ImagemForm
from core.models import Imagem

import requests
import json

import imp
import codecs

def home(request):
	if request.method == 'POST':
		image = Imagem(file=request.FILES['uploaded_file_1'], qtd_followers=request.POST['qtd_followers'])
		image.save()
		
		prefix = 'C:\\Users\\barre\\Documents\\projeto-multimidia\\projeto-multimidia\\backend\\network4like\\media\\'
		i = open(prefix + image.file.name, 'rb')

		api_key = 'acc_05cd943bb73fdbb'
		api_secret = 'bf19cef5ee73254c26e47746004a8155'
		
		print(image.file.url)
		response = requests.post('https://api.imagga.com/v1/content',
			auth=(api_key, api_secret),
			files={'image': i})
		result = response.json()

		content_id = result['uploaded'][0]['id']

		response = requests.get('https://api.imagga.com/v1/tagging?content=%s' % content_id,
                        auth=(api_key, api_secret))

		result = response.json()
		print(str(result))
		columns = ['person', 'adult', 'people', 'caucasian', 'attractive', 
		'happy', 'lifestyle', 'pretty', 'smile', 'model', 'portrait', 'lady', 
		'women', 'body', 'fashion', 'human', 'smiling', 'one', 'sexy', 'cute']

		tags = result["results"][0]["tags"]
		row = []
		for column in columns:
			if len([row.append(x["confidence"]) for x in tags if x['tag'] == column]) <= 0:
				row.append(0)

		# print(row)

		row.append(int(request.POST['qtd_followers']))
		print(row)
		script = imp.load_source('resultado', 'C:\\Users\\barre\\Documents\\projeto-multimidia\\projeto-multimidia\\resultado.py')
		likes = script.treinamento(row)
		print('NUMPY???')
		print(str(likes))
		print(str(result))	
		
		image.qtd_likes = int(likes)
		image.save()
		context = {
			'images': image
		}

		return render(request, 'results.html', context)

	else:
		return render(request, 'index.html')

def exibir(request, pk):
	image = Imagem.objects.get(id=pk)
	context = {
			'images': image
	}
	return render(request, 'results.html', context)

	

backend/network4like/core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Network4Like</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="../static/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="../static/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
    <nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="{% url 'core:index' %}" class="brand-logo">Network4Like</a>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>

    <div id="index-banner" class="parallax-container" style="height: 500px">
        <div class="section no-pad-bot">
            <div class="container">
                <!-- <br><br> -->
                <h1 class="header center  text-lighten-2">Network4Like</h1>
                <!-- <h1></h1> -->
                <div class="row center" style="top: 150px; position: relative">
                    <h3 class="header col s12 light" style="font-weight: 500; ">Ferramenta de auxilo à sua visibilidade no Instagram</h3>
                </div>
                
            </div>
        </div>
        <div class="parallax"><img class="responsive-img" src="../static/image/background.jpg" alt="Unsplashed background img 1"></div>
    </div>

    <div class="container" style="height: 300px; ">
        <div class="section" style="text-align: center;">
        <h3 style="font-size: 2.5rem;">Qual das suas fotos terá mais likes no Instagram?</h3>
        </div>
        <div class="row center" style="margin: 0 222px;">
            <form action="/" enctype="multipart/form-data" method="post">{% csrf_token %}
                 <div class="file-field input-field" style="width: 500px; float: left;">
                    <div class="btn teal darken-1" style="margin-top: 8px;height: 36px;line-height: 36px;margin-right: 10px;">
                        <span>Primeira foto</span>
                        <input type="file" name="uploaded_file_1" required>
                    </div>
                    <div class="file-path-wrapper" style="padding: 0px;">
                        <input class="file-path validate" type="text">
                    </div>
                </div>
                <!--<div class="file-field input-field" style="width: 500px; float: left;">
                    <div class="btn teal darken-1" style="margin-top: 8px;height: 36px;line-height: 36px;margin-right: 10px;">
                        <span>Segunda foto</span>
                        <input type="file" name="uploaded_file_2" >
                    </div>
                    <div class="file-path-wrapper" style="padding: 0px;">
                        <input class="file-path validate" type="text">
                    </div>
                </div>
                <div class="file-field input-field" style="width: 500px; float: left;">
                    <div class="btn teal darken-1" style="margin-top: 8px;height: 36px;line-height: 36px;margin-right: 10px;">
                        <span>Terceira foto</span>
                        <input type="file" name="uploaded_file_3" >
                    </div>
                    <div class="file-path-wrapper" style="padding: 0px;">
                        <input class="file-path validate" type="text">
                    </div>
                </div> -->
                <div class="input-field"  style="width: 200px; float: left;">
                    <input type="number" name="qtd_followers" id="followers" required>
                    <label for="followers">Quantidade de Followers</label>
                </div>
                <button class="btn waves-effect waves-light teal darken-1" type="submit" name="action" style="margin-top: 25px;float: right;">Enviar
                    <i class="material-icons right">send</i>
                </button>  
            </form>
        </div>
    </div>

    <footer class="page-footer teal darken-4">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Sobre</h5>
                    <p class="grey-text text-lighten-4">Projeto desenvolvido para a disciplina de Introdução a Multimidia. Utilizando API Google Plataform e uma rede neural desenvolvida em python</p>
                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Componentes</h5>
                    <ul>
                        <li><a class="white-text" href="https://www.facebook.com/dias.jailson4">Jailson Dias</a></li>
                        <li><a class="white-text" href="https://www.facebook.com/lLeonardoAlvs">Leonardo Alves</a></li>
                        <li><a class="white-text" href="https://www.facebook.com/luiz.neto.900">Luiz Reis</a></li>
                        <li><a class="white-text" href="https://www.facebook.com/marcos.barreto.3720">Marcos Barreto</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>

    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="../static/js/materialize.js"></script>
    <script src="../static/js/init.js"></script>

    </body>
</html>

backend/network4like/core/templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Resultado</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="../static/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="../static/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
    <nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="{% url 'core:index' %}" class="brand-logo">Network4Like</a>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>

    <div id="index-banner" class="container" style="vertical-align: middle; margin-top: 15px">

        <div class="row" style="min-height: 520px;">
            <div class="col s6" style="width: 640px">
                <img class="responsive-img" src="{{ images.file.url }}"></div>
                <div class="col s4" style="text-align: center;vertical-align: middle; ">
                    <h1 class="teal-text text-accent-4" style="">{{images.qtd_likes}} likes</h1>
                </div>
            </div>
        </div>
    </div>

    <footer class="page-footer teal">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">About</h5>
                    <p class="grey-text text-lighten-4">Projeto Desenvolvido para a disciplina de Introdução a Multimidia. Utilizando API Google Plataform e uma rede neural desenvolvida em python</p>
                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Compenentes</h5>
                    <ul>
                        <li><a class="white-text" href="https://www.facebook.com/dias.jailson4">Jailson Dias</a></li>
                        <li><a class="white-text" href="https://www.facebook.com/lLeonardoAlvs">Leonardo Alves</a></li>
                        <li><a class="white-text" href="https://www.facebook.com/luiz.neto.900">Luiz Reis</a></li>
                        <li><a class="white-text" href="https://www.facebook.com/marcos.barreto.3720">Marcos Barreto</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>

<!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="../static/js/materialize.js"></script>
    <script src="../static/js/init.js"></script>

    </body>
</html>